# CO library setup
#N.S = B.S BECAUSE MY INITIALS ARE STUPID
# -- N.S
#MAKE THE WINDOW
  # -- N.S
  #USE ARCADE LIBRARY TO CREATE A WINDOW FOR THE GAME
#SCREEN RESOLUTION
  #1920x1080
#MAKE CHARACTER
  #EDWARD
#MAKE GRAVITY
#MAKE DODGE MECHANIC
#MAKE HITBOXES
#BALANCING
#AGONY
